#!/bin/bash

mv cctry.pgn games/$RANDOM$RAMDOM.pgn

tc="tc=0/10+0.1"

e1="-engine conf=coalface  $tc"
e2="-engine conf=candidate $tc"

t="-event soaktest -tournament round-robin -games 20000"

r="-resign movecount=3 score=400"

d="-draw movenumber=40 movecount=8 score=10"

o="-repeat -srand $RANDOM -openings file=books/4moves_noob.pgn format=pgn order=random plies=16"

f="-pgnout cctry.pgn fi"

s="-sprt elo0=0 elo1=5 alpha=0.05 beta=0.05"

v="-ratinginterval 10"

m="-recover -concurrency 4"

echo $e1 $e2 $t $r $d $o $f $v $m $s

./cutechess $e1 $e2 $t $r $d $o $f $v $m $s
